Repository soham0005/ElectroKart, pull requests merged in 2024-11, with the labels that each got.

#295 Multi-Language Support Using Language Translator
  frontend/package-lock.json
  frontend/src/components/Footer.jsx
  frontend/src/components/GoogleTranslate.css
  frontend/src/components/GoogleTranslate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#294 Create SECURITY.md
  SECURITY.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#214 Fixed the Carousel navigation buttons and the text
  frontend/src/components/Slider.jsx
  frontend/src/styles/slider.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#299 Changes made to ExclusiveOffers and made it visible.
  frontend/src/components/ExclusiveOffers.jsx
  frontend/src/components/Home.jsx
  frontend/src/styles/ExclusiveOffers.css
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1
