Repository soham0005/ElectroKart, pull requests merged in 2024-10, with the labels that each got.

#10 Fixed PreNavbar to Sticky
  package-lock.json
  src/styles/PreNavbar.css
Labels: gssoc-ext, level-1

#27 Create contributing.md issue no(#26)
  contributing.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#66 Update README.md Issue no #61 Resolved
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#65 Added a Favicon and implemented lazy loading for images
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/components/Accessories.jsx
  frontend/src/components/Banner.jsx
  frontend/src/components/ItemCard.jsx
  frontend/src/components/OfferSection/Offer.jsx
  frontend/src/components/ProducReviewCard.jsx
  frontend/src/components/Slider.jsx
  frontend/src/components/StarProducts.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#60 Feature/bannerswipe
  frontend/package-lock.json
  frontend/src/components/Banner.jsx
  frontend/src/components/Slider.jsx
  frontend/src/styles/slider.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#79 FAQs-feature
  frontend/src/components/AllRoutes.jsx
  frontend/src/components/FAQ-feature/FAQ.jsx
  frontend/src/components/PreNavbar.jsx
  frontend/src/styles/FAQ.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#44 Improved Responsiveness
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Banner.jsx
  frontend/src/components/PreNavbar.jsx
  frontend/src/components/Slider.jsx
  frontend/src/styles/Accessories.css
  frontend/src/styles/AccessoriesProduct.css
  frontend/src/styles/Footer.css
  frontend/src/styles/Heading.css
  frontend/src/styles/Navbar.css
  frontend/src/styles/Offers.css
  frontend/src/styles/PreFooter.css
  frontend/src/styles/PreNavbar.css
  frontend/src/styles/ProductReviewCard.css
  frontend/src/styles/ProductReviews.css
  frontend/src/styles/Slider.css
  frontend/src/styles/StarProduct.css
  frontend/src/styles/Videos.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#116 Added links to icons
  frontend/src/components/Banner.jsx
  frontend/src/components/Footer.jsx
  frontend/src/styles/PreFooter.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#124 Fixed alignment of featured section and added active class for the accessories tab
  frontend/src/components/AccessoriesMenu.jsx
  frontend/src/styles/Accessories.css
  frontend/src/styles/StarProduct.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#128 feat: added error page
  frontend/src/App.js
  frontend/src/components/AllRoutes.jsx
  frontend/src/components/page404.jsx
  frontend/src/styles/page404.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#129 Added LICENSE to project.
  LICENSE
  frontend/src/styles/slider.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#130 solved issue #106
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Scrolltotop.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#118 Login Page and signup page Testing with Backend
  backend/controllers/authController.js
  frontend/src/components/User/Login.jsx
  frontend/src/components/User/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#150 redirect to homepage on logo click
  frontend/src/components/PreNavbar.jsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level1

#155 made changes to code...
  backend/index.js
  backend/models/schema.js
  backend/routes/routes.js
  backend/schema.js
  frontend/src/styles/Slider.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#163 Register button and Profile Icon Status Chnaged based on Login Status #153
  backend/.env.example
  backend/index.js
  backend/package-lock.json
  backend/package.json
  frontend/.env.sample
  frontend/src/components/PreNavbar.jsx
  frontend/src/components/User/Login.jsx
  frontend/src/components/User/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#162 Add Missing Subscribe Button and Implement Welcome Email Functionality
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Footer.jsx
  frontend/src/styles/PreFooter.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#158 added scrollbar styling and fixed scrollbar coming
  frontend/src/styles/FAQ.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#183 Checked the Schema.js and added a few changes
  backend/db.js
  backend/index.js
  backend/models/schema.js
  frontend/package-lock.json
  frontend/package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#182 BUG: Apply Password Validation
  frontend/src/components/User/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#189 added language translator to the website
  frontend/src/components/Footer.jsx
  frontend/src/styles/Footer.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#194 Added CI/CD workflow
  .github/workflows/ci-cd.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#218 Changed the Design of signup and login page
  frontend/src/components/PreNavbar.jsx
  frontend/src/components/User/Login.jsx
  frontend/src/components/User/Signup.jsx
  frontend/src/styles/Login.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#220 Search bar
  frontend/src/components/CollapsibleSearchBar.jsx
  frontend/src/components/PreNavbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#224 Fix the ISSUE #138 Add the 'Rate Us' Feature.
  frontend/src/components/Footer.jsx
  frontend/src/styles/Footer.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#230 feat : Added Down Arrow Icon to the FAQS section
  frontend/package-lock.json
  frontend/src/components/FAQ-feature/FAQ.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#202 Design new Footer
  frontend/src/components/Footer.jsx
  frontend/src/components/StarProducts.jsx
  frontend/src/styles/Footer.css
  frontend/src/styles/StarProduct.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#242 improve social media icons , preloader and scroll bar
  frontend/package-lock.json
  frontend/src/components/FAQ-feature/FAQ.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Home.jsx
  frontend/src/components/User/Login.jsx
  frontend/src/components/User/Signup.jsx
  frontend/src/preloader.js
  frontend/src/styles/Footer.css
  frontend/src/styles/PreFooter.css
  frontend/src/styles/preloaderStyle.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#259 Changes made to the backend.
  backend/.env.example
  backend/db.js
  backend/index.js
  backend/models/offersModel.js
  backend/models/ordersModel.js
  backend/models/productsModel.js
  backend/models/schema.js
  backend/models/trendingsModel.js
  backend/models/whislistModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  backend/routes/orderRoutes.js
  backend/routes/productRoutes.js
  backend/routes/routes.js
  frontend/src/components/AllRoutes.jsx
  frontend/src/components/Home.jsx
  frontend/src/components/User/ForgotPassword.jsx
  frontend/src/components/User/Login.jsx
  frontend/src/components/User/Signup.jsx
  frontend/src/styles/StarProduct.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#266 fix: dynamic updater
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#273 Improve mobile responsiveness of the page
  frontend/src/styles/contact.css
  frontend/src/styles/slider.css
Labels: gssoc-ext, level2

#281 fix: resolve infinite loading at faq page
  frontend/src/components/FAQ-feature/FAQ.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#283 Added Table in Readme to display Statistics
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#272 Adding LogIn via OTP #151 (Backend Schema and routes)
  backend/controllers/authController.js
  backend/helpers/authHelper.js
  backend/models/otpModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3
